[tool.flake8]
extend-ignore = "E203"
exclude=['.git','__pycache__',"old","build","dist","venv","env","migrations"]
max-complexity=10
max-line-length=127


[tool.black]
line-length = 127
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
  | venv
  | .idea
  | __pycache__

)/
'''