# Generated by Django 4.2.9 on 2024-01-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_field', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
