# Generated by Django 4.2.9 on 2024-01-28 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_services_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-id']},
        ),
    ]
