# Generated by Django 4.2.9 on 2024-01-28 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whole_sale", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wholesale",
            options={"ordering": ["-id"]},
        ),
    ]
